resource_group_name          = "my-new-rg"
resource_group_location      = "West Europe"
virtual_network_name         = "vnetprod019"
subnet_name                  = "subnet019"
network_interface_name       = "nicprod019"
windows_virtual_machine_name = "windowsvm019"
statename                    = "dev.tfstate"
